---
title: "descriptive_stats"
output: pdf_document
date: "2025-11-19"
---

```{r, message=FALSE}
rm(list=ls())
library(data.table)   # fread
library(ggplot2)
library(DT)          # datatable output
library(scales)
library(lme4)
library(MuMIn)
library(plotly)

learning_curve_csv = "01_runs/regression_resnet101/2025-11-20_10-59-32/epoch_results.csv"
total_lines <- R.utils::countLines(learning_curve_csv)
learning_curve <- fread(learning_curve_csv, nrows = total_lines - 2)

md_csv = "predictions.csv"
metadata <- fread(md_csv)

metadata = metadata[IS_VALID == TRUE]
metadata[, DRYMASS_MG_PRED := (BF_PRED*ROI_SIZE_MM)^3 ]
metadata[, cbrDRYMASS_MG := DRYMASS_MG^ (1/3)]
metadata[, cbrDRYMASS_MG_PRED := DRYMASS_MG_PRED^ (1/3)]
metadata[, sqrtAREA_MM := AREA_MM2^(1/2)]
```

## Data overview

``` {r, message=FALSE}
ggplot(metadata, aes(cbrDRYMASS_MG, sqrtAREA_MM, shape=DATASET, colour=DATASET)) + 
    geom_point(alpha=.6)  + 
    geom_smooth(method = "lm") +
    facet_grid( . ~ SPLIT)
metadata[, .N, by=c("DATASET", "SPLIT")]
```
## Area-based biomass prediction
```{r, message=FALSE}
# area_model <- lm(cbrDRYMASS_MG ~ sqrtAREA_MM * DATASET, metadata[SPLIT == "train"])
area_model <- lm(cbrDRYMASS_MG ~ sqrtAREA_MM , metadata[SPLIT == "train"])
summary(area_model)
metadata[, cbrDRYMASS_MG_PRED_AREA_LM := predict(area_model, metadata)]
lims <- range(c(metadata$cbrDRYMASS_MG, metadata$cbrDRYMASS_MG_PRED_AREA_LM))
ggplot(metadata[SPLIT == "test"],
       aes(cbrDRYMASS_MG, 
           cbrDRYMASS_MG_PRED_AREA_LM, 
           shape=DATASET, colour=DATASET)) +
  geom_point() + geom_smooth(method = "lm") +
  coord_fixed(xlim = lims, ylim = lims)
mod <- lm(cbrDRYMASS_MG_PRED_AREA_LM ~ cbrDRYMASS_MG, metadata[SPLIT == "test"])
summary(mod)

```
## CNN-based biomass prediction
```{r, message=FALSE}
ggplot(learning_curve, aes(epoch, train_loss)) + 
  geom_line(colour="blue") +
  geom_line(aes(y=val_loss), colour="red")  + 
  scale_y_continuous(name="loss (train: blue, val: red)")
  
lims <- range(c(metadata$cbrDRYMASS_MG, metadata$cbrDRYMASS_MG_PRED))
ggplot(metadata[SPLIT == "test"], 
       aes(cbrDRYMASS_MG, 
           cbrDRYMASS_MG_PRED, 
           shape=DATASET, 
           colour=DATASET)) +
  geom_point() + 
  geom_smooth(aes(cbrDRYMASS_MG, cbrDRYMASS_MG_PRED), colour="black", fill="black",  inherit.aes = FALSE, method = "lm") + 
  coord_fixed(xlim = lims, ylim = lims)

mod <- lm(cbrDRYMASS_MG_PRED ~ cbrDRYMASS_MG, metadata[SPLIT == "test"])
summary(mod)
```

