---
title: "Biomass analysis"
output: pdf_document
date: "2025-11-19"
---

```{r, message=FALSE}

rm(list=ls())
library(data.table)   # fread
library(ggplot2)
library(DT)          # datatable output
library(scales)
library(lme4)
library(MuMIn)
library(plotly)

library(dplyr)
library(tidyr)

md_csv = "predictions.csv"
metadata <- fread(md_csv)
hist(metadata[,conf])
#filter for high confidence detections!
metadata = metadata[conf > 0.90]

metadata[, DRYMASS_MG_PRED := (BF_PRED*ROI_SIZE_MM)^3 ]
metadata[, cbrDRYMASS_MG_PRED := DRYMASS_MG_PRED^ (1/3)]
metadata[, sqrtAREA_MM := AREA_MM2^(1/2)]


metadata <- metadata %>%
  separate(
    custom_label,
    into = c("ignore", "sample_id", "species", "location", "date"),
    sep = "_",
    remove = FALSE
  ) %>%
  select(-ignore)


metadata <- as.data.table(metadata)
metadata[, date := as.POSIXct(date, format = "%Y-%m-%d")]
metadata[,year := format(date, "%Y")]
metadata[,day_of_year :=  as.numeric(format(date, "%j"))]
```

## Data overview

``` {r, message=FALSE}
library(ggplot2)
library(data.table)
library(ggExtra)

# --- BG plot ---
p <- ggplot(
  metadata[species == "BG"],
  aes(day_of_year, DRYMASS_MG_PRED)
) +
  stat_density_2d(aes(fill = after_stat(density)),
                  geom = "raster",
                  contour = FALSE) +
  scale_fill_gradientn(
    colours = c("#f7fbff", "#c6dbef", "#fddbc7", "#f4a582", "#ca0020")
  ) +
  geom_jitter(width = 2, height = 0, alpha = 0.2)

p_final <- ggMarginal(p, margins = "y", size = 2, type = "histogram")

ggsave("plot_BG.svg",
       plot = p_final,
       width = 7,
       height = 4,
       device = "svg")


# --- PD plot ---
p <- ggplot(
  metadata[species == "PD"],
  aes(day_of_year, DRYMASS_MG_PRED)
) +
  stat_density_2d(aes(fill = after_stat(density)),
                  geom = "raster",
                  contour = FALSE) +
  scale_fill_gradientn(
    colours = c("#f7fbff", "#c6dbef", "#fddbc7", "#f4a582", "#ca0020")
  ) +
  geom_jitter(width = 2, height = 0, alpha = 0.2)

p_final <- ggMarginal(p, margins = "y", size = 2, type = "histogram")

ggsave("plot_PD.svg",
       plot = p_final,
       width = 7,
       height = 4,
       device = "svg")


# --- Histogram ---
ggplot(
  metadata,
  aes(DRYMASS_MG_PRED)
) +
  geom_histogram(fill = "steelblue", color = "black") +
  facet_grid(species ~ .)
```

