---
title: "Biomass analysis"
output: pdf_document
date: "2025-11-19"
---

```{r, message=FALSE}

rm(list=ls())
library(data.table)   # fread
library(ggplot2)
library(DT)          # datatable output
library(scales)
library(lme4)
library(MuMIn)
library(plotly)

library(dplyr)
library(tidyr)

md_csv = "predictions.csv"
metadata <- fread(md_csv)
#filter for high confidence detections!
metadata = metadata[conf > 0.75]

metadata[, DRYMASS_MG_PRED := (BF_PRED*ROI_SIZE_MM)^3 ]
metadata[, cbrDRYMASS_MG_PRED := DRYMASS_MG_PRED^ (1/3)]
metadata[, sqrtAREA_MM := AREA_MM2^(1/2)]


metadata <- metadata %>%
  separate(
    custom_label,
    into = c("ignore", "replicate", "species", "temp", "sex"),
    sep = "_",
    remove = FALSE
  ) %>%
  select(-ignore)

metadata <- metadata %>%
  mutate(
    temp = factor(temp, levels = c("19", "28"), ordered = TRUE)
  )

```

## Data overview

``` {r, message=FALSE}

# pdf()

counts <- metadata %>%
  group_by(species, sex) %>%
  summarise(
    n = n(),
    y = max(cbrDRYMASS_MG_PRED, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(
  metadata,
  aes(species, cbrDRYMASS_MG_PRED, colour = temp)
) +
  facet_wrap(~sex) +
  geom_violin(outlier.colour = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  geom_text(
    data = counts,
    aes(species, y, label = n),
    vjust = -0.4,
    colour = "black",
    inherit.aes = FALSE
  ) + scale_colour_manual(
    values = c(
      "19" = "blue",
      "28" = "red"
    ),
    name = "Temperature (°C)"
  )




counts <- metadata %>%
  group_by(species, sex) %>%
  summarise(
    n = n(),
    y = max(sqrtAREA_MM, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(
  metadata,
  aes(species, sqrtAREA_MM, colour = temp)
) +
  facet_wrap(~sex) +
  geom_violin(outlier.colour = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  geom_text(
    data = counts,
    aes(species, y, label = n),
    vjust = -0.4,
    colour = "black",
    inherit.aes = FALSE
  )
+ scale_colour_manual(
    values = c(
      "19" = "blue",
      "28" = "red"
    ),
    name = "Temperature (°C)"
  )




```
