---
title: "Biomass analysis"
output: pdf_document
date: "2025-11-19"
---

```{r, message=FALSE}

rm(list=ls())
library(data.table)   # fread
library(ggplot2)
library(DT)          # datatable output
library(scales)
library(lme4)
library(MuMIn)
library(plotly)

library(dplyr)
library(tidyr)

md_csv = "predictions.csv"
metadata <- fread(md_csv)

#filter for high confidence detections!
metadata = metadata[conf > 0.90]

metadata[, DRYMASS_MG_PRED := (BF_PRED*ROI_SIZE_MM)^3 ]
metadata[, cbrDRYMASS_MG_PRED := DRYMASS_MG_PRED^ (1/3)]
metadata[, sqrtAREA_MM := AREA_MM2^(1/2)]


metadata <- metadata %>%
  separate(
    custom_label,
    into = c("ignore", "replicate", "species", "temp", "sex"),
    sep = "_",
    remove = FALSE
  ) %>%
  select(-ignore)

metadata <- metadata %>%
  mutate(
    temp = factor(temp, levels = c("19", "28"), ordered = TRUE)
  )
metadata <- as.data.table(metadata)

```

## Data overview

``` {r, message=FALSE}


pdf(w=16, h=9)

# counts <- metadata %>%
#   group_by(species, sex) %>%
#   summarise(
#     n = n(),
#     y = max(cbrDRYMASS_MG_PRED, na.rm = TRUE),
#     .groups = "drop"
#   )

ggplot(
  metadata,
  aes(species, DRYMASS_MG_PRED, colour = temp, fill = temp)
) +
  facet_grid( sex ~ .) +
  geom_violin(
    position = position_dodge(width = 0.9),
    outlier.colour = NA,
    colour = "black"
  ) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.width = 0.15,
      dodge.width = 0.9
    ),
    
    alpha = 0.6,
    colour = "black"
  ) + scale_fill_manual(
    values = c(
      "19" = "blue",
      "28" = "red"
    ),
    name = "Temperature (°C)"
  ) 
  


ggplot(
  metadata,
  aes(species, AREA_MM2, colour = temp, fill = temp)
) +
  facet_grid( sex ~ .) +
  geom_boxplot(
    position = position_dodge(width = 0.9),
    outlier.colour = NA,
    colour = "black"
  ) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.width = 0.15,
      dodge.width = 0.9
    ),
    
    alpha = 0.6,
    colour = "black"
  ) + scale_fill_manual(
    values = c(
      "19" = "blue",
      "28" = "red"
    ),
    name = "Temperature (°C)"
  )


dev.off()
```

```{r}
reps <- lapply(1:2000, function(x){
    spl = metadata[, .(AREA_MM2 = sample(AREA_MM2, size=.N,replace = T)), by="sex,species,temp"]
    out = spl[, .(cvar=sd(AREA_MM2)/mean(AREA_MM2)), by="sex,species,temp"]
    out$rep=x
    out
})
reps = rbindlist(reps)

mean_q025_q975 <- function(x) {
  data.frame(
    y     = mean(x, na.rm = TRUE),
    ymin  = quantile(x, 0.025, na.rm = TRUE),
    ymax  = quantile(x, 0.975, na.rm = TRUE)
  )
}

ggplot(reps, aes(species, cvar, colour = temp)) +
  stat_summary(fun.data = mean_q025_q975) +
  facet_grid(sex ~ .)

```

